[package]
name = "usecases"
version.workspace = true
edition.workspace = true

[lib]
path = "./src/lib.rs"

[dependencies]
services.workspace = true
shared.workspace = true
macros.workspace = true

schemars = "0.8.21"
hyper.workspace = true
tokio.workspace = true
http-body-util.workspace = true

parse-display = "0.10.0"

tracing.workspace = true

mlua.workspace = true

serde_yaml = "0.9.34"
homedir = "0.3.4"

tower.workspace = true
serde-env.workspace = true
serde_json.workspace = true
serde.workspace = true

sysinfo.workspace = true
form_urlencoded.workspace = true
lazy_static.workspace = true
clap.workspace = true
bytes.workspace = true

[dev-dependencies]
serde_derive.workspace = true

