[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"

[dependencies]
macros.workspace = true
plugin_interface = { path = "../../../plugin_interface/" }

tracing.workspace = true

homedir = "0.3.4"

anyhow = "1.0.94"
libloading = "0.8.6"

tokio.workspace = true

mlua.workspace = true

serde_yaml = "0.9.34"

serde-env.workspace = true
serde_json.workspace = true
serde.workspace = true

lazy_static.workspace = true
clap.workspace = true
bytes.workspace = true


[dev-dependencies]
serde_derive.workspace = true
