[package]
name = "services"
version.workspace = true
edition.workspace = true

[lib]
path = "./src/lib.rs"

[dependencies]
shared.workspace = true

tracing.workspace = true

tokio.workspace = true
http-body-util.workspace = true

tower.workspace = true
serde-env.workspace = true
serde_json.workspace = true
serde.workspace = true

sysinfo.workspace = true
form_urlencoded.workspace = true
lazy_static.workspace = true
clap.workspace = true
bytes.workspace = true

reqwest = { version = "0.12.9", features = ["json"] }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["combaseapi", "objbase", "winnls","winuser"] }
windows = { version = "0.58.0", features = [
    "Media_Control",
] }

[build-dependencies]
tonic-build.workspace = true
